---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    openssl_fqdn: server.example.com
    apache_fqdn: "{{ openssl_fqdn }}"
    apache_ssl_key: "{{ openssl_server_key }}"
    apache_ssl_crt: "{{ openssl_server_crt }}"
    apache_ssl_chain: "{{ openssl_server_crt }}"
    nginx_server_name: webmail.example.com
    nginx_ssl_key: "{{ openssl_server_key }}"
    nginx_ssl_crt: "{{ openssl_server_crt }}"
    nginx_root: /var/www/webmail.example.com/public_html
    nginx_logdir: /var/www/webmail.example.com/log
    rainloop_vhost: webmail.example.com
    rainloop_domain: example.com
    rainloop_ssl_key: "{{ openssl_server_key }}"
    rainloop_ssl_crt: "{{ openssl_server_crt }}"
    rainloop_ssl_chain: "{{ openssl_server_crt }}"
    rainloop_path: /var/www/webmail.example.com/public_html
    rainloop_log: /var/www/webmail.example.com/log
    rainloop_web_server: "{{ 'apache' if ansible_os_family == 'RedHat' else 'nginx' }}"
  roles:
    - openssl
    - {'role': 'apache', 'when': "ansible_os_family == 'RedHat'"}
    - {'role': 'nginx', 'when': "ansible_os_family == 'Debian'"}
    - php
  tasks:
    - name: Include role 'ansible-role-rainloop'
      ansible.builtin.include_role:
        name: ansible-role-rainloop
